# -*- coding: utf-8 -*-
"""
Rakkad Aqua — fish care engine.
Care data is built from established care-group envelopes (all Mbuna share care,
all Corydoras share care, etc.), verified against trusted sources (Aquatic Arts
product standard, Seriously Fish, Practical Fishkeeping, species guides). Fields
mirror the Aquatic Arts layout: temperature, pH, hardness (KH), minimum tank
size, diet, social behaviour, origin, adult size, care level, temperament,
lifespan. Rare / unclassifiable imports are held out for manual review rather
than given invented numbers.

Vocab (standardised):
  care        : Beginner | Beginner-Intermediate | Intermediate | Intermediate-Advanced | Advanced
  temperament : Peaceful | Peaceful (with care) | Semi-aggressive | Territorial | Aggressive
  swim        : Top | Middle | Bottom | All levels
"""
import re

CARE_LVL = {"Beginner":1,"Beginner-Intermediate":2,"Intermediate":3,"Intermediate-Advanced":4,"Advanced":5}
TEMP_LVL = {"Peaceful":1,"Peaceful (with care)":2,"Semi-aggressive":3,"Territorial":4,"Aggressive":5}
CARE_COLOR = {"Beginner":"#2FA36B","Beginner-Intermediate":"#6FB05A","Intermediate":"#E0972B",
              "Intermediate-Advanced":"#D9702C","Advanced":"#C6482E"}
TEMP_COLOR = {"Peaceful":"#2FA36B","Peaceful (with care)":"#6FB05A","Semi-aggressive":"#E0972B",
              "Territorial":"#D9702C","Aggressive":"#C6482E"}

def G(**k): return k
# ---- care-group envelopes -----------------------------------------------------
GROUPS = {
"Tetra/Characin": G(family="Characidae", origin="South America", care="Beginner",
    temperament="Peaceful", tempF="72-80°F", tempC="22-27°C", ph="5.5-7.5", hard="Soft-Medium (2-15 dGH)",
    tank="20 gallons", adult="1.5-2.5 in (4-6 cm)", diet="Omnivore", social="Shoal of 6 or more",
    swim="Middle", life="3-5 years",
    desc="{n} is a small, active schooling characin that shows its best colour and behaviour in a group. Peaceful and undemanding, it's ideal for planted community aquariums.",
    tips=["Keep in a shoal of at least 6 — lone specimens are shy and washed-out.",
          "Offer a varied diet of quality micro-pellets, flakes and frozen foods.",
          "Best in a planted tank with open swimming space and gentle flow."]),
"Rasbora": G(family="Cyprinidae", origin="Southeast Asia", care="Beginner",
    temperament="Peaceful", tempF="73-80°F", tempC="23-27°C", ph="5.5-7.0", hard="Soft-Medium (2-12 dGH)",
    tank="10-20 gallons", adult="0.75-2 in (2-5 cm)", diet="Omnivore", social="Shoal of 8 or more",
    swim="Middle", life="3-5 years",
    desc="{n} is a peaceful nano cyprinid that shoals tightly and suits planted and nano aquascapes. Its small size and calm nature make it a community favourite.",
    tips=["Keep 8+ together for a confident, colourful shoal.",
          "Soft, slightly acidic water and planted cover bring out the best colour.",
          "Feed small foods — micro-pellets, crushed flake and frozen daphnia/cyclops."]),
"Barb": G(family="Cyprinidae", origin="Asia", care="Beginner-Intermediate",
    temperament="Semi-aggressive", tempF="72-79°F", tempC="22-26°C", ph="6.0-7.5", hard="Soft-Medium (4-15 dGH)",
    tank="30 gallons", adult="2-3 in (5-8 cm)", diet="Omnivore", social="Shoal of 6 or more",
    swim="Middle", life="5 years",
    desc="{n} is an active, hardy barb. Kept in good numbers it's a lively community fish, but small groups can turn nippy toward long-finned tankmates.",
    tips=["Keep a shoal of 6+ to spread out natural nipping behaviour.",
          "Avoid slow, long-finned tankmates (e.g. bettas, angelfish, guppies).",
          "Provide open swimming space for this fast, energetic fish."]),
"Danio/Minnow": G(family="Cyprinidae", origin="Asia", care="Beginner",
    temperament="Peaceful", tempF="64-77°F", tempC="18-25°C", ph="6.5-7.5", hard="Soft-Medium (5-15 dGH)",
    tank="20 gallons", adult="1-2.5 in (2.5-6 cm)", diet="Omnivore", social="Shoal of 6 or more",
    swim="Top-Middle", life="3-5 years",
    desc="{n} is a hardy, extremely active schooling fish that tolerates cooler water than most tropicals. A great, forgiving choice for community and coldwater-leaning tanks.",
    tips=["Keep a tight-fitting lid — these are energetic jumpers.",
          "Happiest in a shoal of 6+ with long open swimming lanes.",
          "Tolerates cooler room-temperature water; avoid overheating."]),
"Guppy/Endler": G(family="Poeciliidae", origin="Central/South America (livebearer)", care="Beginner",
    temperament="Peaceful", tempF="72-82°F", tempC="22-28°C", ph="7.0-8.0", hard="Medium-Hard (8-20 dGH)",
    tank="10-20 gallons", adult="1-2.5 in (2.5-6 cm)", diet="Omnivore", social="Groups (more females than males)",
    swim="Top-Middle", life="2-3 years",
    desc="{n} is a colourful, hardy livebearer and one of the easiest fish in the hobby. It breeds readily and thrives in harder, alkaline water.",
    tips=["Prefers harder, alkaline water — avoid soft, acidic setups.",
          "Keep 2-3 females per male to reduce harassment of females.",
          "Breeds prolifically; provide plant cover for fry or expect a growing colony."]),
"Molly/Platy/Swordtail": G(family="Poeciliidae", origin="Central America (livebearer)", care="Beginner",
    temperament="Peaceful", tempF="72-82°F", tempC="22-28°C", ph="7.0-8.2", hard="Medium-Hard (10-25 dGH)",
    tank="20-30 gallons", adult="2-5 in (5-13 cm)", diet="Omnivore (veg-leaning)", social="Groups",
    swim="Middle", life="3-5 years",
    desc="{n} is a hardy, peaceful livebearer that does best in hard, alkaline water with plenty of vegetable matter in its diet. An easy, active community fish.",
    tips=["Hard, alkaline water keeps these livebearers healthiest (mollies especially).",
          "Include algae/veg-based foods — blanched vegetables and spirulina.",
          "Keep in groups; expect regular broods of live young."]),
"Goldfish": G(family="Cyprinidae (coldwater)", origin="Selectively bred (China)", care="Beginner-Intermediate",
    temperament="Peaceful", tempF="65-75°F", tempC="18-24°C", ph="7.0-8.4", hard="Medium-Hard (8-20 dGH)",
    tank="20-30 gallons per fish", adult="6-8 in fancy (15-20 cm)", diet="Omnivore", social="Groups",
    swim="All levels", life="10-15+ years",
    desc="{n} is a hardy coldwater fish that needs no heater but produces a heavy bioload, so strong filtration and space are essential. A long-lived, personable pet.",
    tips=["Coldwater fish — no heater needed; keep below ~24°C.",
          "Big bioload: over-filter and do generous water changes.",
          "Feed sinking foods to fancy types to reduce swim-bladder/buoyancy issues."]),
"Koi": G(family="Cyprinidae (pond)", origin="Selectively bred (Japan)", care="Intermediate",
    temperament="Peaceful", tempF="59-77°F", tempC="15-25°C", ph="7.0-8.5", hard="Medium-Hard (8-20 dGH)",
    tank="Pond, 250+ gallons", adult="24-36 in (60-90 cm)", diet="Omnivore", social="Groups",
    swim="All levels", life="20-30+ years",
    desc="{n} is a pond fish, not an aquarium fish — it reaches 60-90 cm and lives for decades. It needs a large pond with powerful filtration and aeration.",
    tips=["A POND fish: an aquarium is only suitable for short-term grow-out.",
          "Plan for a very large adult size and heavy filtration.",
          "Tolerates cool water well; feed less as temperatures drop."]),
"Betta": G(family="Osphronemidae", origin="Southeast Asia", care="Beginner",
    temperament="Aggressive", tempF="76-82°F", tempC="24-28°C", ph="6.0-7.5", hard="Soft-Medium (2-15 dGH)",
    tank="5 gallons", adult="2.5-3 in (6-8 cm)", diet="Carnivore", social="Solitary (one male per tank)",
    swim="Top-Middle", life="3-5 years",
    desc="{n} is a labyrinth fish that breathes air from the surface. Males are beautiful but territorial and must be kept one to a tank; they prefer warm, still water.",
    tips=["One male per tank — males fight, sometimes to the death.",
          "Warm, stable water and gentle flow (strong currents stress them).",
          "Carnivore: feed betta pellets plus frozen bloodworms/brine shrimp."]),
"Gourami/Anabantid": G(family="Osphronemidae", origin="Southeast Asia", care="Beginner-Intermediate",
    temperament="Peaceful (with care)", tempF="74-82°F", tempC="23-28°C", ph="6.0-7.5", hard="Soft-Medium (4-15 dGH)",
    tank="20-30 gallons", adult="2-6 in (5-15 cm)", diet="Omnivore", social="Pairs or single",
    swim="Top-Middle", life="3-5 years",
    desc="{n} is a labyrinth fish that gulps air at the surface and appreciates calm water. Generally peaceful, though males can be territorial with their own kind.",
    tips=["Keep calm water with surface access for air-breathing.",
          "Avoid keeping multiple males in a small tank — they turn territorial.",
          "Provide floating plants and gentle flow for a secure, settled fish."]),
"Angelfish": G(family="Cichlidae", origin="Amazon, South America", care="Intermediate",
    temperament="Semi-aggressive", tempF="78-84°F", tempC="25-29°C", ph="6.0-7.5", hard="Soft-Medium (3-15 dGH)",
    tank="30 gallons (tall)", adult="6 in tall, to 8 in (15-20 cm)", diet="Omnivore", social="Pairs / small groups",
    swim="Middle", life="8-10 years",
    desc="{n} is a graceful South American cichlid with a tall body that needs a deep tank. Peaceful for a cichlid, but pairs get territorial when breeding and may eat very small fish.",
    tips=["Use a tall tank to accommodate the fins and body shape.",
          "May eat very small fish (e.g. neon tetras) — choose tankmates by size.",
          "Warm, soft-to-neutral water; pairs become territorial when spawning."]),
"Discus": G(family="Cichlidae", origin="Amazon, South America", care="Advanced",
    temperament="Peaceful", tempF="82-88°F", tempC="28-31°C", ph="5.5-7.0", hard="Soft (1-8 dGH)",
    tank="55+ gallons (group)", adult="6-8 in (15-20 cm)", diet="Omnivore/Carnivore", social="Groups of 6+",
    swim="Middle", life="10-15 years",
    desc="{n} is the 'king of the aquarium' — a stunning but demanding cichlid needing very warm, soft, pristine water and a group for security. Best for experienced keepers.",
    tips=["Keep very warm (28-31°C) — warmer than most community fish.",
          "Soft, acidic, spotless water with frequent large water changes.",
          "Keep 6+ to reduce bullying; feed high-quality varied foods often."]),
"Dwarf Cichlid (Apisto/Ram)": G(family="Cichlidae", origin="South America", care="Intermediate",
    temperament="Peaceful (with care)", tempF="78-84°F", tempC="26-29°C", ph="5.5-7.0", hard="Soft (2-10 dGH)",
    tank="20-30 gallons", adult="2-3.5 in (5-9 cm)", diet="Carnivore/Omnivore", social="Pairs",
    swim="Bottom-Middle", life="2-4 years",
    desc="{n} is a colourful dwarf cichlid best kept as a pair in warm, soft water with caves and territory. Peaceful in a community, but defends a small breeding territory.",
    tips=["Warm, soft, slightly acidic water suits dwarf cichlids best.",
          "Provide caves and broken sight-lines so a pair can hold territory.",
          "Rams (Mikrogeophagus) want the warm end (28-30°C) and stable water."]),
"African Rift Cichlid (Malawi)": G(family="Cichlidae", origin="Lake Malawi, East Africa", care="Intermediate",
    temperament="Aggressive", tempF="76-82°F", tempC="24-28°C", ph="7.8-8.6", hard="Hard / Alkaline (10-20 dGH)",
    tank="55 gallons", adult="4-6 in (10-15 cm)", diet="Omnivore", social="Groups (species-appropriate)",
    swim="All levels", life="8-10 years",
    desc="{n} is a colourful, boldly territorial Lake Malawi cichlid. It needs hard, alkaline water and a rocky, cave-filled aquascape, with stocking planned to spread aggression.",
    tips=["Hard, alkaline water is essential — not for soft-water community tanks.",
          "Build rockwork with many caves; keep them appropriately stocked to diffuse aggression.",
          "Mbuna need veg-based food (avoid excess protein → Malawi bloat); peacocks/haps take more protein."]),
"Tanganyikan Cichlid": G(family="Cichlidae", origin="Lake Tanganyika, East Africa", care="Intermediate",
    temperament="Territorial", tempF="76-82°F", tempC="24-28°C", ph="7.8-9.0", hard="Hard / Alkaline (10-20 dGH)",
    tank="30-55 gallons (species-dependent)", adult="2-14 in — varies by species", diet="Carnivore/Omnivore",
    social="Colony or pair (species-dependent)", swim="All levels", life="8-15 years",
    desc="{n} is a Lake Tanganyika cichlid needing hard, alkaline water. This group ranges from tiny shell-dwellers to large Frontosa, so check the specific species' adult size and setup.",
    tips=["Hard, alkaline water with the right decor — shells for shell-dwellers, rock for others.",
          "Adult size varies enormously across this group — confirm the species before stocking.",
          "Feed appropriately: many are micro-predators; avoid excess for the smaller species."]),
"Eartheater/Geophagus": G(family="Cichlidae", origin="South America", care="Intermediate",
    temperament="Peaceful (with care)", tempF="78-86°F", tempC="26-30°C", ph="5.5-7.5", hard="Soft-Medium (2-12 dGH)",
    tank="75 gallons", adult="6-12 in (15-30 cm)", diet="Omnivore (sand-sifter)", social="Groups",
    swim="Bottom", life="10+ years",
    desc="{n} is a large but generally peaceful 'eartheater' that sifts sand for food. It needs a big tank, warm soft water and a fine sand bed to show natural behaviour.",
    tips=["Use a fine sand substrate so it can sift naturally (protects gills).",
          "Warm, soft water and a spacious tank; best kept in groups.",
          "Peaceful for its size, but plan for a large adult and heavy bioload."]),
"SA/CA Cichlid (large)": G(family="Cichlidae", origin="Central/South America", care="Intermediate-Advanced",
    temperament="Aggressive", tempF="74-82°F", tempC="23-28°C", ph="6.5-7.5", hard="Medium (5-20 dGH)",
    tank="55-125 gallons (species-dependent)", adult="6-16 in — varies by species", diet="Carnivore/Omnivore",
    social="Solitary or bonded pair", swim="All levels", life="10-15 years",
    desc="{n} is a large, characterful New World cichlid. These fish are intelligent and territorial, needing a big tank, strong filtration and robust decor. Adult size varies widely by species.",
    tips=["Provide a large tank with powerful filtration and secure hardscape.",
          "Territorial and often aggressive — choose tankmates carefully and confirm the species' temperament.",
          "Confirm the exact species' adult size before stocking — some exceed 30 cm."]),
"Cichlid (other)": G(family="Cichlidae", origin="Varies", care="Intermediate",
    temperament="Semi-aggressive", tempF="74-82°F", tempC="23-28°C", ph="6.5-8.0", hard="Medium (5-20 dGH)",
    tank="40-55 gallons", adult="4-8 in — varies by species", diet="Omnivore", social="Species-dependent",
    swim="All levels", life="8-12 years",
    desc="{n} is a cichlid whose exact requirements depend on its species and region. As a group these fish are territorial and appreciate structured decor and defined territories.",
    tips=["Confirm the species' origin (African rift vs. New World) to set the right water hardness.",
          "Provide territory and broken sight-lines to reduce aggression.",
          "Match tankmates to the species' adult size and temperament."]),
"Snakehead": G(family="Channidae", origin="Asia / Africa", care="Intermediate-Advanced",
    temperament="Aggressive", tempF="72-82°F", tempC="22-28°C", ph="6.0-7.5", hard="Soft-Medium (5-15 dGH)",
    tank="55-125 gallons (species-dependent)", adult="6-40 in — varies hugely by species", diet="Carnivore",
    social="Solitary or bonded pair", swim="All levels", life="10-15 years",
    desc="{n} is a predatory air-breathing snakehead. Species range from ~15 cm dwarves to metre-long giants, so the exact species dictates tank size. All are escape artists and hunters.",
    tips=["A tight, weighted lid is essential — snakeheads are determined jumpers.",
          "Predatory: do not house with fish small enough to be eaten.",
          "Confirm the species' adult size before buying — it ranges from 15 cm to over 1 m."]),
"Pleco (L-number/Bristlenose)": G(family="Loricariidae", origin="South America", care="Beginner-Intermediate",
    temperament="Peaceful (with care)", tempF="75-82°F", tempC="24-28°C", ph="6.0-7.5", hard="Soft-Medium (2-15 dGH)",
    tank="30 gallons (varies by species)", adult="4-18 in — varies by species", diet="Omnivore",
    social="Solitary (can be territorial)", swim="Bottom", life="10-15 years",
    desc="{n} is a loricariid catfish. Sizes range from a 12 cm bristlenose to an 45 cm+ common pleco, so confirm the species. Most graze biofilm and need driftwood and sinking foods.",
    tips=["Provide driftwood — many species rasp on wood as part of their diet.",
          "Don't rely on tank algae alone; offer sinking wafers and vegetables (Hypancistrus are carnivores).",
          "Confirm adult size before buying — bristlenose stay ~12 cm, common/sailfin plecos exceed 40 cm."]),
"Corydoras": G(family="Callichthyidae", origin="South America", care="Beginner",
    temperament="Peaceful", tempF="72-79°F", tempC="22-26°C", ph="6.0-7.5", hard="Soft-Medium (2-15 dGH)",
    tank="20 gallons", adult="1-3 in (2.5-8 cm)", diet="Omnivore (bottom)", social="Shoal of 6 or more",
    swim="Bottom", life="5-8 years",
    desc="{n} is a peaceful, sociable bottom-dwelling catfish that shoals and constantly forages. A superb, hardy community cleanup fish that's happiest in a group.",
    tips=["Use smooth sand or rounded gravel to protect their delicate barbels.",
          "Keep 6+ together — Corydoras are highly social and stressed when alone.",
          "Feed sinking foods; don't assume they'll survive on leftovers alone."]),
"Otocinclus": G(family="Loricariidae", origin="South America", care="Intermediate",
    temperament="Peaceful", tempF="72-79°F", tempC="22-26°C", ph="6.0-7.5", hard="Soft-Medium (2-15 dGH)",
    tank="20 gallons", adult="1.5-2 in (4-5 cm)", diet="Herbivore (algae/biofilm)", social="Shoal of 6 or more",
    swim="Bottom", life="3-5 years",
    desc="{n} is a tiny, peaceful algae-grazing catfish. It needs a mature tank with steady biofilm and gentle handling — sensitive to poor water and bare, new setups.",
    tips=["Add only to a mature, biofilm-rich tank — new tanks starve them.",
          "Keep a group of 6+; supplement with algae wafers and blanched vegetables.",
          "Very sensitive to water quality and acclimation — go slow."]),
"Catfish (other)": G(family="Siluriformes", origin="Varies", care="Intermediate",
    temperament="Peaceful (with care)", tempF="72-82°F", tempC="22-28°C", ph="6.0-7.8", hard="Soft-Medium (5-15 dGH)",
    tank="40-125 gallons (species-dependent)", adult="3-24 in — varies by species", diet="Omnivore/Carnivore",
    social="Species-dependent", swim="Bottom", life="8-15 years",
    desc="{n} is a catfish whose needs depend heavily on species. Many are nocturnal and appreciate caves; some (e.g. Synodontis) stay moderate while others (shovelnose, redtail) grow very large.",
    tips=["Provide caves and shaded retreats — many catfish are nocturnal.",
          "Confirm the species' adult size before buying; some grow far too large for home tanks.",
          "Feed after lights-out with sinking foods to ensure they get enough."]),
"Loach": G(family="Cobitidae / Botiidae", origin="Asia", care="Beginner-Intermediate",
    temperament="Peaceful (with care)", tempF="75-82°F", tempC="24-28°C", ph="6.0-7.5", hard="Soft-Medium (3-15 dGH)",
    tank="30-75 gallons (species-dependent)", adult="2-12 in — varies by species", diet="Omnivore",
    social="Groups of 5 or more", swim="Bottom", life="10-15 years",
    desc="{n} is a social bottom-dwelling loach that does best in groups and appreciates smooth substrate and hiding spots. Some stay small; clown loaches grow large and long-lived.",
    tips=["Keep in groups of 5+ — loaches are social and pine when kept singly.",
          "Use smooth substrate and provide caves/tunnels for security.",
          "Many relish snails; confirm adult size (clown loach reaches ~30 cm)."]),
"Hillstream Loach": G(family="Balitoridae", origin="Asia (fast rivers)", care="Intermediate",
    temperament="Peaceful", tempF="68-75°F", tempC="20-24°C", ph="7.0-8.0", hard="Medium-Hard (8-15 dGH)",
    tank="20-30 gallons", adult="2-3 in (5-8 cm)", diet="Herbivore (aufwuchs)", social="Groups",
    swim="Bottom", life="8-10 years",
    desc="{n} is a river specialist adapted to cool, fast, oxygen-rich water. It grazes biofilm from smooth stones and needs strong flow — not a standard warm community fish.",
    tips=["Provide strong flow and high oxygen — a river-manifold or powerhead setup.",
          "Keep cooler than typical tropicals (20-24°C); avoid warm, still water.",
          "Grazes biofilm/algae off smooth rocks; supplement with veg and biofilm."]),
"Rainbowfish": G(family="Melanotaeniidae", origin="Australia / New Guinea", care="Beginner-Intermediate",
    temperament="Peaceful", tempF="74-82°F", tempC="23-28°C", ph="7.0-8.0", hard="Medium-Hard (8-20 dGH)",
    tank="30 gallons", adult="2-5 in (5-13 cm)", diet="Omnivore", social="Shoal of 6 or more",
    swim="Middle-Top", life="5-8 years",
    desc="{n} is an active, peaceful schooling fish whose colours intensify with age and in a group. It prefers neutral-to-hard water and plenty of open swimming space.",
    tips=["Keep 6+ — colour and confidence build in a shoal (and with mature males).",
          "Neutral to slightly alkaline, harder water suits them well.",
          "Give long open swimming lanes; they're fast, active swimmers."]),
"Killifish/Ricefish": G(family="Aplocheilidae / Adrianichthyidae", origin="Varies", care="Intermediate",
    temperament="Peaceful (with care)", tempF="68-79°F", tempC="20-26°C", ph="6.0-7.5", hard="Soft-Medium (3-12 dGH)",
    tank="10-20 gallons", adult="1-3 in (2.5-8 cm)", diet="Carnivore (micro)", social="Pairs or small groups",
    swim="Top-Middle", life="1-3 years",
    desc="{n} is a small, jewel-like killifish/ricefish. Many prefer soft water and take small live/frozen foods; males can spar, so provide cover and watch groupings.",
    tips=["Keep a tight lid — many killifish are accomplished jumpers.",
          "Offer small live/frozen foods (some ignore dry food).",
          "Provide dense planting/cover; watch male-to-male sparring."]),
"Pencilfish/Hatchet": G(family="Lebiasinidae / Gasteropelecidae", origin="South America", care="Intermediate",
    temperament="Peaceful", tempF="74-82°F", tempC="23-28°C", ph="5.5-7.0", hard="Soft (2-10 dGH)",
    tank="20 gallons", adult="1-2.5 in (2.5-6 cm)", diet="Carnivore (micro/surface)", social="Shoal of 6 or more",
    swim="Top", life="3-5 years",
    desc="{n} is a peaceful surface-oriented shoaler. Pencilfish and hatchets take small foods from the top and need calm water, cover and — for hatchets especially — a secure lid.",
    tips=["Keep a tight-fitting lid — hatchetfish are champion jumpers.",
          "Offer small floating/surface foods and frozen micro-foods.",
          "Soft water, gentle flow and a shoal of 6+ keep them settled."]),
"Silver Dollar/Large Characin": G(family="Characidae / Serrasalmidae", origin="South America", care="Intermediate",
    temperament="Peaceful", tempF="75-82°F", tempC="24-28°C", ph="5.5-7.5", hard="Soft-Medium (4-18 dGH)",
    tank="75 gallons", adult="5-8 in (13-20 cm)", diet="Herbivore", social="Shoal of 5 or more",
    swim="Middle", life="10 years",
    desc="{n} is a large, peaceful, disc-shaped characin that shoals and appreciates space. Most are avid plant-eaters, so pair with tough or artificial plants.",
    tips=["Keep a group of 5+ in a large tank — they're skittish when few.",
          "Expect them to eat soft plants; use robust or artificial plants.",
          "Provide open swimming space and secure the tank (they spook and dash)."]),
"Goby": G(family="Gobiidae", origin="Varies", care="Intermediate",
    temperament="Peaceful (with care)", tempF="72-79°F", tempC="22-26°C", ph="7.0-8.0", hard="Medium-Hard (8-15 dGH)",
    tank="10-20 gallons", adult="1-3 in (2.5-8 cm)", diet="Carnivore", social="Pairs or single",
    swim="Bottom", life="3-5 years",
    desc="{n} is a small bottom goby, often territorial over a favourite cave. Some are strictly freshwater grazers while others (e.g. bumblebee gobies) prefer brackish water — check the species.",
    tips=["Confirm freshwater vs. brackish needs for the exact species.",
          "Offer small live/frozen foods; many ignore dry flake.",
          "Provide caves/territories — gobies defend a small patch."]),
"Badis/Dario": G(family="Badidae", origin="Asia", care="Intermediate",
    temperament="Peaceful (with care)", tempF="72-79°F", tempC="22-26°C", ph="6.5-7.5", hard="Soft-Medium (5-15 dGH)",
    tank="10-20 gallons", adult="0.8-3 in (2-8 cm)", diet="Carnivore (micro)", social="Pairs / harem",
    swim="Bottom-Middle", life="3-5 years",
    desc="{n} is a small, shy micro-predator (such as the scarlet badis). It often refuses dry food, needs gentle tankmates and dense cover, and rewards patience with jewel-like colour.",
    tips=["Feed small live/frozen foods — most refuse flakes and pellets.",
          "Keep with calm, small tankmates; boisterous fish outcompete them.",
          "Provide dense planting and cover so this shy fish feels secure."]),
"Shark (cyprinid)": G(family="Cyprinidae", origin="Southeast Asia", care="Intermediate",
    temperament="Territorial", tempF="72-79°F", tempC="22-26°C", ph="6.5-7.5", hard="Soft-Medium (5-15 dGH)",
    tank="55 gallons", adult="5-6 in (13-15 cm)", diet="Omnivore", social="Single (bala shark: groups)",
    swim="All levels", life="8-10 years",
    desc="{n} is an active 'shark' cyprinid. Red-tail and rainbow sharks are territorial and best kept singly; bala 'sharks' are peaceful but grow large and need a group and a big tank.",
    tips=["Red-tail / rainbow sharks: keep one per tank — they chase their own kind.",
          "Bala sharks are gentle but reach ~30 cm and need a group + very large tank.",
          "Provide a long tank with territory and hiding spots."]),
"Pufferfish": G(family="Tetraodontidae", origin="Varies", care="Intermediate-Advanced",
    temperament="Aggressive", tempF="74-82°F", tempC="23-28°C", ph="7.0-7.8", hard="Medium-Hard (8-15 dGH)",
    tank="20-125 gallons (species-dependent)", adult="1-24 in — varies hugely by species", diet="Carnivore",
    social="Usually solitary", swim="All levels", life="5-10+ years",
    desc="{n} is an intelligent but nippy puffer. Species range from the 2.5 cm pea puffer to giant fahaka/mbu; some are freshwater and some brackish. Most need hard, snail-based foods to wear their teeth.",
    tips=["Confirm freshwater vs. brackish and adult size for the exact species.",
          "Feed hard-shelled foods (snails, crustaceans) to keep the teeth worn down.",
          "Often nippy or predatory — many must be kept alone."]),
"Oddball/Predator": G(family="Various", origin="Varies", care="Intermediate-Advanced",
    temperament="Aggressive", tempF="75-82°F", tempC="24-28°C", ph="6.5-7.5", hard="Soft-Medium (5-15 dGH)",
    tank="75-300+ gallons (species-dependent)", adult="6-48 in — varies hugely by species", diet="Carnivore",
    social="Solitary or species-dependent", swim="All levels", life="10-20 years",
    desc="{n} is a specialist 'oddball' predator (such as bichirs, arowana, gar, knifefish or eels). Most grow large and hunt, so the exact species dictates tank size and tankmates.",
    tips=["Use a tight, weighted lid — most oddball predators jump or climb.",
          "Predatory: never house with fish small enough to be swallowed.",
          "Research the exact species — many outgrow standard aquariums dramatically."]),
"Algae Eater/Misc": G(family="Cyprinidae", origin="Southeast Asia", care="Beginner",
    temperament="Peaceful (with care)", tempF="72-79°F", tempC="22-26°C", ph="6.5-7.8", hard="Soft-Medium (5-15 dGH)",
    tank="30-50 gallons", adult="4-6 in (10-16 cm)", diet="Omnivore (algae-leaning)", social="Single or group of 6+",
    swim="Bottom", life="8-10 years",
    desc="{n} is an active algae-grazing fish. True Siamese Algae Eaters are peaceful and among the few fish that eat black beard algae, but they need supplemental food and a secure lid.",
    tips=["Supplement algae grazing with algae wafers and blanched vegetables.",
          "Active jumper — keep a secure lid; provide moderate flow and oxygen.",
          "Keep singly or in a group of 6+ (avoid the aggressive Chinese Algae Eater)."]),
}

# ---- species-level overrides (keyword -> field patches; raise accuracy) -------
OVERRIDES = [
 (r"oscar", dict(adult="12-14 in (30-36 cm)", tank="75 gallons", temperament="Aggressive", care="Intermediate")),
 (r"flowerhorn|flower horn", dict(adult="12-16 in (30-40 cm)", tank="75 gallons", temperament="Aggressive")),
 (r"jaguar", dict(adult="14-16 in (35-40 cm)", tank="125 gallons", temperament="Aggressive")),
 (r"\bmanaguense|dovii|umbee|motaguense", dict(adult="14-24 in (35-60 cm)", tank="180 gallons", temperament="Aggressive")),
 (r"green terror|jack dempsey|\btexas\b", dict(adult="8-12 in (20-30 cm)", tank="75 gallons", temperament="Aggressive")),
 (r"convict|firemouth|salvini|\brainbow cichlid\b", dict(adult="4-6 in (10-15 cm)", tank="40 gallons")),
 (r"keyhole|\bport\b", dict(adult="4-5 in (10-13 cm)", tank="40 gallons", temperament="Peaceful (with care)")),
 (r"severum|\buaru\b", dict(adult="8-12 in (20-30 cm)", tank="75 gallons", temperament="Semi-aggressive")),
 (r"parrot", dict(adult="7-8 in (18-20 cm)", tank="55 gallons", temperament="Semi-aggressive")),
 (r"frontosa|gibberosa", dict(adult="12-14 in (30-35 cm)", tank="125 gallons", temperament="Semi-aggressive")),
 (r"shell dweller|multifasciat|similis|ocellatus|brevis", dict(adult="1.5-2.5 in (4-6 cm)", tank="20 gallons")),
 (r"clown loach", dict(adult="10-12 in (25-30 cm)", tank="75 gallons", social="Groups of 5+")),
 (r"bala shark", dict(adult="10-13 in (25-33 cm)", tank="125 gallons", temperament="Peaceful", social="Groups of 5+")),
 (r"red tail shark|red-tail shark|rainbow shark", dict(adult="5-6 in (13-15 cm)", temperament="Territorial", social="Single")),
 (r"common pleco|sailfin pleco|gibbiceps|leopard sailfin", dict(adult="15-18 in (38-45 cm)", tank="125 gallons")),
 (r"bristlenose|ancistrus", dict(adult="4-5 in (10-13 cm)", tank="30 gallons")),
 (r"zebra pleco|\bl046\b|\bl 046\b|l333|l134|hypancistrus", dict(adult="3-4 in (8-10 cm)", care="Advanced", diet="Carnivore", tank="30 gallons")),
 (r"pea puffer|dwarf puffer", dict(adult="1-1.5 in (2.5-3.5 cm)", tank="10 gallons", temperament="Semi-aggressive", hard="Soft-Medium (5-12 dGH)")),
 (r"fahaka|\bmbu\b", dict(adult="16-30 in (40-75 cm)", tank="180 gallons", temperament="Aggressive")),
 (r"figure 8|figure.8", dict(adult="2.5-3 in (6-8 cm)", tank="20 gallons")),
 (r"arowana|arawana", dict(adult="24-36 in (60-90 cm)", tank="250 gallons")),
 (r"\bgar\b|alligator gar", dict(adult="24-48 in (60-120 cm)", tank="300 gallons")),
 (r"bichir|polypterus|senegal|delhezi|endlicheri|ornate", dict(adult="12-28 in (30-70 cm)", tank="90 gallons")),
 (r"aba aba|knifefish|black ghost", dict(adult="8-20 in (20-50 cm)", tank="90 gallons")),
 (r"discus", dict(care="Advanced")),
 (r"german blue ram|electric blue ram|\bram\b", dict(tempF="82-86°F", tempC="28-30°C", care="Intermediate-Advanced")),
 (r"kribensis|\bkrib\b", dict(family="Cichlidae", origin="West Africa", adult="3-4 in (8-10 cm)", tank="20 gallons", temperament="Peaceful (with care)", ph="6.0-7.5", hard="Soft-Medium (5-12 dGH)")),
 (r"mahseer", dict(adult="18-36 in (45-90 cm)", tank="250 gallons", temperament="Semi-aggressive")),
 (r"redtail cat|red tail cat|tiger shovelnose|shovelnose", dict(adult="24-48 in (60-120 cm)", tank="300 gallons", temperament="Aggressive")),
 (r"comet|common goldfish|shubunkin|sarasa|wakin", dict(adult="10-12 in (25-30 cm)", tank="75 gallons / pond")),
]

# ---- classifier + parsers -----------------------------------------------------
RULES = [
 ('Goldfish', r'goldfish|ranchu|oranda|ryukin|pearlscale|pingpong|ping pong|lionhead|fantail|bubble eye|telescope|shubunkin|wakin|celestial eye|pom ?pom|lionchu|\bveil ?tail\b|comet|sarasa'),
 ('Koi', r'\bkoi\b'),
 ('Betta', r'\bbetta\b|plakat|halfmoon|half moon|crowntail|crown tail|\bhmpk\b|elephant ear|dumbo ear|\bveiltail betta\b'),
 ('Guppy/Endler', r'guppy|endler'),
 ('Molly/Platy/Swordtail', r'molly|platy|swordtail|variatus'),
 ('Discus', r'discus'),
 ('Snakehead', r'channa|snakehead'),
 ('Dwarf Cichlid (Apisto/Ram)', r'apistogramma|apisto|mikrogeophagus|microgeophagus|ramirezi|\bram\b|\brams\b|dicrossus|checkerboard cichlid|nannacara|laetacara|kribensis|\bkrib\b|pelvicachromis'),
 ('Angelfish', r'angelfish|angel fish|pterophyllum|\baltum\b'),
 ('Tanganyikan Cichlid', r'tanganyik|tropheus|julidochromis|masked julie|cyprichromis|cyprochromis|neolamprologus|lamprologus|altolamprologus|frontosa|cyphotilapia|calvus|compressiceps|shell dweller|multifasciat|brichardi|leleupi|petrochromis|paracyprichromis|enantiopus|xenotilapia|ocellatus|similis|brevis'),
 ('African Rift Cichlid (Malawi)', r'mbuna|malawi|pseudotropheus|labidochromis|yellow lab|metriaclima|maylandia|melanochromis|aulonocara|peacock cichlid|protomelas|cynotilapia|demasoni|\bacei\b|\bhap\b|placidochromis|sciaenochromis|copadichromis|otopharynx|victoria|pundamilia|thumbi|perlmutt|peacock|livingston|empress|blue dolphin|strawberry cichlid|kodango|johani|eureka|sunshine|\bahli\b|borleyi|venustus|electric blue|dragon blood|taiwan reef|ruby red|german red|nimbochromis|\bzebra cichlid\b|red top|kenyi|auratus|socolofi|rusty cichlid|electric yellow|tropheops|petrotilapia|mpanga|chitimba|red empress'),
 ('Eartheater/Geophagus', r'geophagus|eartheater|earth eater|biotodoma|gymnogeophagus|satanoper|jurupari|acarichthys|guianacara|demon earth'),
 ('SA/CA Cichlid (large)', r'oscar|severum|festae|jack dempsey|convict|firemouth|green terror|\btexas\b|flowerhorn|flower horn|\buaru\b|pike cichlid|crenicichla|\bvieja\b|midas|red devil|salvini|jaguar|wolf cichlid|blood parrot|\bparrot\b|keyhole|chocolate cichlid|heckel|\bmacaw\b|amphilophus|herichthys|thorichthys|parachromis|andinoacara|cryptoheros|nandopsis|rocio|paratilapia|\bacara\b|managuense|motaguense|umbee|dovii|trimac|honduran red|rainbow cichlid|\bport\b'),
 ('Pleco (L-number/Bristlenose)', r'pleco|plecostomus|bristlenose|ancistrus|hypancistrus|panaque|panaqolus|\bl\s?\d{2,3}\b|\blda\s?\d+\b|zebra pleco|clown pleco|cactus pleco|snowball pleco|medusa pleco|leopard frog pleco|sailfin pleco|rubber lip|farlowella|whiptail'),
 ('Hillstream Loach', r'hillstream|sewellia|gastromyzon|butterfly loach'),
 ('Corydoras', r'corydoras|\bcory\b|\bcorys\b|\bcorydora\b|sterbai|habrosus|pygmaeus|\baeneus\b|panda cory|julii'),
 ('Otocinclus', r'otocinclus|\boto\b'),
 ('Catfish (other)', r'synodontis|pictus|woodcat|banjo cat|glass cat|upside.?down|raphael|bumblebee cat|\bcatfish\b|debauwi|featherfin|dianema|hoplo|porthole|driftwood cat|pimelodus|\bpim\b|redtail cat|red tail cat|shovelnose|\bchaca\b|\baba aba\b'),
 ('Loach', r'\bloach\b|botia|kuhli|yoyo|dojo|weather loach|acanthophthalmus|nemacheilus|schistura|pangio'),
 ('Rasbora', r'rasbora|harlequin|boraras|trigonostigma|microdevario|chili rasbora|emerald dwarf|kubotai'),
 ('Danio/Minnow', r'\bdanio\b|zebrafish|celestial pearl|galaxy rasbora|white cloud|\bminnow\b|microrasbora|leopard danio|glowlight danio|rosy loach'),
 ('Rainbowfish', r'rainbow|melanotaenia|praecox|boesemani|celebes|threadfin|pseudomugil|blue eye|iriatherina|gertrudae'),
 ('Killifish/Ricefish', r'\bkilli|killifish|nothobranchius|aphyosemion|fundulopanchax|gardneri|clown killi|ricefish|medaka|epiplatys|panchax|golden wonder|american flag|flagfish|flag fish'),
 ('Gourami/Anabantid', r'gourami|paradise fish|licorice|sparkling gour|honey gour|pearl gour|chocolate gour|samurai|trichogaster|trichopodus|colisa|sphaerichthys|kissing|snakeskin'),
 ('Badis/Dario', r'\bbadis\b|\bdario\b|scarlet badis'),
 ('Goby', r'\bgoby\b|stiphodon|rhinogobius|bumblebee goby|peacock goby|mudskipper'),
 ('Pencilfish/Hatchet', r'pencilfish|pencil fish|nannostomus|hatchet'),
 ('Silver Dollar/Large Characin', r'silver dollar|metynnis|\bpacu\b|headstander|leporinus|abramites|\bdollar\b'),
 ('Barb', r'\bbarb\b|\bbarbs\b|puntius|pethia|denison|odessa|dawkinsia'),
 ('Tetra/Characin', r'tetra|characin|hyphessobrycon|hemigrammus|pristella|emperor|\bember\b|rummy.?nose|\bneon\b|cardinal|serpae|x-?ray|black skirt|phantom|glowlight|jellybean|bleeding heart|von rio|buenos aires|\bcongo\b|\binpa\b|arrow tetra|amapa'),
 ('Shark (cyprinid)', r'\bshark\b|epalzeorhynchos|flying fox'),
 ('Pufferfish', r'puffer|figure 8|fahaka|\bmbu\b'),
 ('Oddball/Predator', r'archer|arowana|arawana|peacock bass|datnoid|\bdat\b|\bgar\b|bichir|polypterus|senegal|delhezi|endlicheri|knifefish|\bknife\b|elephant nose|rope ?fish|stingray|\bray\b|\beel\b|butterfly fish|leaf fish|tiger ?fish|wolf ?fish|barracuda|\btrout\b|hilltrout|mahseer|alligator|glassfish|glass fish'),
 ('Algae Eater/Misc', r'algae eater|siamese algae|garra|chinese algae'),
 ('Cichlid (other)', r'cichlid|mbuna|\bcichlids\b'),
]
def classify(t):
    t = t.lower()
    for name, pat in RULES:
        if re.search(pat, t): return name
    return None  # -> REVIEW

def parse_size(title):
    m = re.search(r'(\d+(?:\.\d+)?)\s*(?:-\s*(\d+(?:\.\d+)?)\s*)?(inch|in\b|"|cm|CM)', title, re.I)
    if not m: return ""
    a,b,unit = m.group(1), m.group(2), m.group(3).lower().replace('"','in')
    unit = 'cm' if 'cm' in unit else 'in'
    return f"{a}-{b} {unit}" if b else f"{a} {unit}"

def clean_name(title):
    n = title
    n = re.sub(r'\*[^*]*\*', ' ', n)                                     # *rare*
    n = re.sub(r'\([^)]*\)', ' ', n)                                     # (Pair),(Import),(Male Only)
    n = re.sub(r'\d+(?:\.\d+)?\s*(?:-\s*\d+(?:\.\d+)?)?\s*(?:inches|inch|in|cm|mm)\b', ' ', n, flags=re.I)
    n = re.sub(r'\d+(?:\.\d+)?\s*(?:-\s*\d+(?:\.\d+)?)?\s*"', ' ', n)     # 4.5" / 3-4"
    n = re.sub(r'\b(?:xxxl|xxl|xl|jumbo|small|medium|large|\bsml\b|\bsm\b|\blg\b|\bmd\b)\b', ' ', n, flags=re.I)
    n = re.sub(r'\b(?:import|imported|wild|\bwc\b|tank[- ]?bred|\btb\b|\bnew\b|rare|super\s*rare|assorted|male only|female only)\b', ' ', n, flags=re.I)
    n = re.sub(r'[\"\'”“]', ' ', n)
    n = re.sub(r'\s{2,}', ' ', n).strip(' -–—/,+')
    return n or title.strip()

def apply_overrides(title, env):
    t = title.lower(); env = dict(env)
    for pat, patch in OVERRIDES:
        if re.search(pat, t): env.update(patch)
    return env
print("fish groups:", len(GROUPS), "| overrides:", len(OVERRIDES))

# ---- AQA feeding range (real SKUs found in store complementary-products) ------
AQA_FOODS = {
 "eco":     ("AQA Micro Pellet (Economy)",        "aqa-micro-pellet-economy",          "everyday staple pellet"),
 "colour":  ("AQA Micro Pellet Colour-Enhancing", "aqa-micro-pellet-colour-enhancing", "daily colour-boosting pellet"),
 "cichlid": ("AQA Cichlid Colour Enhancer",       "aqa-cichlid-colour-enhancer",       "colour-enhancing cichlid food"),
 "brine":   ("AQA Brineshrimp Flakes",            "aqa-brineshrimp-flakes",            "high-protein conditioning flake"),
}
# group -> (primary, treat, supplement-note)   note='' when the range already covers the diet
FOOD_MAP = {
 "Tetra/Characin":("colour","brine",""), "Rasbora":("colour","brine",""),
 "Danio/Minnow":("colour","brine",""), "Barb":("colour","brine",""),
 "Rainbowfish":("colour","brine",""), "Guppy/Endler":("colour","brine",""),
 "Molly/Platy/Swordtail":("colour","brine","Add algae/vegetable matter for this veg-leaning livebearer."),
 "Goldfish":("eco","","Feed a sinking staple plus vegetable matter; avoid overfeeding."),
 "Koi":("eco","","Use a pond staple sized to the fish; add vegetable matter."),
 "Betta":("colour","brine",""), "Gourami/Anabantid":("colour","brine",""),
 "Angelfish":("cichlid","brine",""), "Discus":("cichlid","brine","Feed several small meals of high-protein food daily."),
 "Dwarf Cichlid (Apisto/Ram)":("cichlid","brine",""),
 "African Rift Cichlid (Malawi)":("cichlid","brine","Mbuna are veg-leaning — keep protein moderate to avoid bloat."),
 "Tanganyikan Cichlid":("cichlid","brine",""),
 "Eartheater/Geophagus":("cichlid","brine",""),
 "SA/CA Cichlid (large)":("cichlid","brine","Larger specimens need bigger meaty/pellet foods."),
 "Cichlid (other)":("cichlid","brine",""), "Snakehead":("brine","","Predatory — feed meaty foods sized to the fish."),
 "Pleco (L-number/Bristlenose)":("eco","","Supplement with algae wafers, vegetables and driftwood (Hypancistrus need meaty food)."),
 "Corydoras":("eco","brine","Use a sinking pellet so this bottom-feeder gets its share."),
 "Otocinclus":("eco","","Primarily an algae/biofilm grazer — supplement with vegetable matter."),
 "Catfish (other)":("eco","brine","Feed after lights-out; larger/predatory species need meaty foods."),
 "Loach":("eco","brine","Use a sinking food; many also relish snails."),
 "Hillstream Loach":("eco","","Mainly grazes biofilm/algae — supplement with vegetable matter."),
 "Killifish/Ricefish":("brine","colour","Prefers small live/frozen foods; some ignore dry food."),
 "Pencilfish/Hatchet":("colour","brine","Feed small surface/floating foods."),
 "Silver Dollar/Large Characin":("eco","","Largely herbivorous — supplement with vegetable matter and greens."),
 "Goby":("brine","","Offer small live/frozen foods; many ignore flake."),
 "Badis/Dario":("brine","","Usually needs live/frozen micro-foods — may refuse dry food."),
 "Shark (cyprinid)":("colour","brine",""),
 "Pufferfish":("brine","","Needs hard-shelled foods (snails, crustaceans) to wear down its teeth."),
 "Oddball/Predator":("brine","","Predatory — feed meaty foods sized to the fish; large species need large prey items."),
 "Algae Eater/Misc":("eco","","Grazes algae — supplement with algae wafers and vegetables."),
}
def food_rec(group):
    pk, tk, note = FOOD_MAP.get(group, ("colour","brine",""))
    out = {"primary": AQA_FOODS[pk], "treat": AQA_FOODS[tk] if tk else None, "note": note}
    return out
